services:
  punchingbag:
    build:
      context: ./punching-bag
    restart: unless-stopped
    container_name: punchingbag
    networks:
      - funny
    #volumes:
    #  - second-volume:/home
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    container_name: theboy
    networks:
      - funny
    volumes:
      - gamerbot-store:/gb-data
    depends_on:
      - punchingbag

volumes:
  gamerbot-store:
  #second-volume:

networks:
  funny:
    driver: bridge
